# Generated by Django 5.2 on 2025-04-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
