# Generated by Django 5.2 on 2025-04-19 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_alter_contact_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="status",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional status selected from predefined choices.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contacts.contactstatuschoices",
            ),
        ),
    ]
