name: CI - Format & Security Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff bandit safety django

      - name: Check formatting with Black
        run: black --check .

      - name: Check import order with isort
        run: isort . --check-only

      - name: Run Ruff linter
        run: ruff check .

      - name: Run Bandit (Security Scan)
        run: bandit -r . -ll -iii

      - name: Audit dependencies with pip-audit
        run: |
          pip install pip-audit
          pip-audit

      - name: Django Security Checks
        run: |
          python manage.py check --deploy --fail-level WARNING

      - name: Run Tests
        run: |
          python manage.py migrate
          python manage.py test