name: CI - Format & Security Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv and project dependencies
        run: |
          pip install uv
          UV_NO_CACHE=1 uv pip install --system --extra dev --lock uv.lock

      - name: Set environment variables
        run: |
          echo "SECRET_KEY=ci-secret-key-for-testing" >> .env
          echo "DEBUG=False" >> .env
          echo "ALLOWED_HOSTS=127.0.0.1,localhost" >> .env

      - name: Check formatting with Black
        run: black --check .

      - name: Check import order with isort
        run: isort . --check-only

      - name: Run Ruff linter
        run: ruff check .

      - name: Run Bandit (Security Scan)
        run: bandit -r . -ll -iii

      - name: Audit dependencies with pip-audit
        run: pip-audit

      - name: Run Django security checks
        run: python manage.py check --deploy --fail-level ERROR

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test
